import { useState, useEffect, useCallback } from 'react';

export type Language = 'en' | 'ar';

export const translations = {
  en: {
    'nav.work': 'Work',
    'nav.beforeAfter': 'Before / After',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'header.subtitle': 'Editorial Designer',
    'hero.available': 'Available for Projects',
    'hero.specialist': 'Medical Content Specialist',
    'hero.typed': 'Designer',
    'hero.typedAlt1': 'Typesetter',
    'hero.typedAlt2': 'Educator',
    'hero.typedAlt3': 'Specialist',
    'hero.bio': 'Crafting Educational content, academic books, structured PDFs, and materials for universities, colleges, and institutions — with deep specialisation in the medical field.',
    'hero.bioAr': 'تصميم محتوى تعليمي احترافي يخدم الطلاب والمعلمين والمؤسسات التعليمية.',
    'hero.cta1': 'View My Work',
    'hero.cta2': 'Start Your Project',
    'hero.cta2Ar': 'ابدأ مشروعك',
    'stat1.label': '+ Book Layouts',
    'stat2.label': '+ PDF Documents',
    'stat3.label': 'Medical Institutions',
    'stat4.label': 'Years Experience',
    'work.title': 'Selected Works',
    'work.subtitle': 'A curated selection — want to see more? Download the full portfolio below.',
    'filter.all': 'All',
    'filter.books': 'Books & PDF',
    'filter.presentations': 'Presentations',
    'filter.mindmaps': 'Mind Maps',
    'filter.summaries': 'Summaries',
    'work.ctaTitle': 'Want to see more samples?',
    'work.ctaBtn': 'Request Portfolio',
    'work.ctaBtnAr': 'اطلب الملف الكامل',
    'testimonials.title': 'Trusted by those who need',
    'testimonials.titleHighlight': 'clarity.',
    'testimonials.subtitle': 'Real words from clients — clearer files, faster review, ready to publish.',
    'testimonial1.name': 'د. محمد العمر',
    'testimonial1.role': 'طب الأسرة · مسار للتعليم الطبي',
    'testimonial2.name': 'Sarah A.',
    'testimonial2.role': 'Academic Review Lead · Medical Education',
    'ba.title': 'Drag the line and see the',
    'ba.titleHighlight': 'difference.',
    'ba.subtitle': 'A professional before/after presentation that stays responsive, keyboard-friendly, and ready for your real case files.',
    'ba.arLabel': 'قبل وبعد',
    'ba.case1': 'Behavior Science',
    'ba.case1Hint': 'حرّك المؤشر لمقارنة التصميم.',
    'ba.case2': 'Clinical Summary',
    'ba.case2Hint': 'مناسب لعرض الملفات بأي اتجاه.',
    'ba.ctaTitle': 'Ready for your own transformation?',
    'ba.ctaBtn': 'Start Now',
    'ba.ctaBtnAr': 'ابدأ الآن',
    'services.title': 'What I Offer',
    'services.heading': 'Services built for',
    'services.headingHighlight': 'impact.',
    'services.tagline': 'من فكرة إلى تصميم محترف.',
    'services.cta': 'Free Consultation',
    'services.ctaAr': 'احجز استشارة مجانية',
    'service1.title': 'Books & PDF',
    'service1.titleAr': 'كتب وملفات PDF',
    'service1.desc': 'Full layout, typesetting, medical textbooks & digital publications — print-ready.',
    'service2.title': 'Presentations',
    'service2.titleAr': 'عروض تقديمية',
    'service2.desc': 'Medical lectures, conferences & institutional slides that communicate with authority.',
    'service3.title': 'Mind Maps',
    'service3.titleAr': 'خرائط ذهنية',
    'service3.desc': 'Visual pathways & clinical diagrams that make complexity instantly clear.',
    'service4.title': 'Summaries & Q-Banks',
    'service4.titleAr': 'ملخصات وبنوك أسئلة',
    'service4.desc': 'MCQ banks, study cards & visual digests that compress complexity into clarity.',
    'about.title': 'About Me',
    'about.heading': 'Where design meets',
    'about.headingHighlight': 'medicine.',
    'about.bio1': "I'm Dr Abdurrahman M. Hafez, a Cairo-based medical content designer and editorial specialist with a deep focus on the medical and academic fields.",
    'about.bio2': "Well-designed medical content doesn't just look good — it helps students learn faster, doctors recall better, and institutions communicate with authority.",
    'about.tools': 'Tools & Software',
    'about.experience': 'Experience',
    'contact.title': 'Start a Conversation',
    'contact.heading': "Let's make something",
    'contact.headingHighlight': 'worth reading.',
    'contact.tagline': 'لنصنع شيئاً يستحق القراءة.',
    'contact.waLabel': 'Fastest Response',
    'contact.waTitle': 'Chat on WhatsApp',
    'contact.waHint': 'أرد في دقائق.',
    'contact.emailLabel': 'Email',
    'contact.emailTitle': 'hello@hafez.design',
    'contact.locationLabel': 'Based in',
    'contact.locationTitle': 'Cairo, Egypt · Remote Worldwide',
    'contact.locationAr': 'القاهرة، مصر · متاح للعمل عن بُعد',
    'contact.formTitle': 'Send a message',
    'contact.formHint': 'أو راسلني مباشرة على واتساب لرد أسرع.',
    'contact.nameLabel': 'Name *',
    'contact.namePlaceholder': 'Your name',
    'contact.nameError': 'Please enter your name.',
    'contact.emailLabel2': 'Email *',
    'contact.emailPlaceholder': 'you@example.com',
    'contact.emailError': 'Please enter a valid email.',
    'contact.serviceLabel': 'Service *',
    'contact.servicePlaceholder': 'Select a service…',
    'contact.serviceError': 'Please select a service.',
    'contact.messageLabel': 'Message *',
    'contact.messagePlaceholder': 'Tell me about your project…',
    'contact.messageError': 'Please enter a message.',
    'contact.submitBtn': 'Send Message',
    'contact.waBtn': 'راسلني على واتساب',
    'contact.directEmail': 'Or email directly: hello@hafez.design',
    'footer.name': 'Dr Abdurrahman M.',
    'footer.backToTop': 'Back to top',
    'footer.copyright': '2026',
    'toast.message': "Message sent — I'll reply within 24 hours.",
  },
  ar: {
    'nav.work': 'أعمالي',
    'nav.beforeAfter': 'قبل وبعد',
    'nav.services': 'خدماتي',
    'nav.about': 'نبذة',
    'nav.contact': 'تواصل',
    'header.subtitle': 'مصمم محتوى طبي ومحرر',
    'hero.available': 'متاح للمشاريع',
    'hero.specialist': 'متخصص محتوى طبي',
    'hero.typed': 'مصمم',
    'hero.typedAlt1': 'مفضّل',
    'hero.typedAlt2': 'معلّم',
    'hero.typedAlt3': 'متخصص',
    'hero.bio': 'تصميم محتوى تعليمي احترافي، كتب أكاديمية، ملفات PDF منظمة، ومواد تعليمية للجامعات والكليات والمؤسسات — مع تخصص عميق في المجال الطبي.',
    'hero.bioAr': 'تصميم محتوى تعليمي احترافي يخدم الطلاب والمعلمين والمؤسسات التعليمية.',
    'hero.cta1': 'شاهد أعمالي',
    'hero.cta2': 'ابدأ مشروعك',
    'hero.cta2Ar': 'ابدأ مشروعك',
    'stat1.label': '+ تصميم كتب',
    'stat2.label': '+ ملفات PDF',
    'stat3.label': 'مؤسسات طبية',
    'stat4.label': 'سنوات خبرة',
    'work.title': 'أعمال مختارة',
    'work.subtitle': 'مجموعة مختارة — تريد المزيد؟ حمّل الملف الكامل أدناه.',
    'filter.all': 'الكل',
    'filter.books': 'كتب و PDF',
    'filter.presentations': 'عروض تقديمية',
    'filter.mindmaps': 'خرائط ذهنية',
    'filter.summaries': 'ملخصات',
    'work.ctaTitle': 'تريد رؤية المزيد من النماذج؟',
    'work.ctaBtn': 'اطلب الملف الكامل',
    'work.ctaBtnAr': 'اطلب الملف الكامل',
    'testimonials.title': 'موثوق به من يحتاجون إلى',
    'testimonials.titleHighlight': 'الوضوح.',
    'testimonials.subtitle': 'كلمات حقيقية من العملاء — ملفات أوضح، مراجعة أسرع، جاهزة للنشر.',
    'testimonial1.name': 'د. محمد العمر',
    'testimonial1.role': 'طب الأسرة · مسار للتعليم الطبي',
    'testimonial2.name': 'Sarah A.',
    'testimonial2.role': 'Academic Review Lead · Medical Education',
    'ba.title': 'اسحب الخط وشاهد',
    'ba.titleHighlight': 'الفرق.',
    'ba.subtitle': 'عرض احترافي قبل/بعد يظل متجاوبًا ويعمل بالكيبورد وجاهز لملفاتك الحقيقية.',
    'ba.arLabel': 'قبل وبعد',
    'ba.case1': 'علم السلوك',
    'ba.case1Hint': 'حرّك المؤشر لمقارنة التصميم.',
    'ba.case2': 'الملخص السريري',
    'ba.case2Hint': 'مناسب لعرض الملفات بأي اتجاه.',
    'ba.ctaTitle': 'جاهز لتحويل ملفاتك؟',
    'ba.ctaBtn': 'ابدأ الآن',
    'ba.ctaBtnAr': 'ابدأ الآن',
    'services.title': 'ما أقدمه',
    'services.heading': 'خدمات مصممة لـ',
    'services.headingHighlight': 'التأثير.',
    'services.tagline': 'من فكرة إلى تصميم محترف.',
    'services.cta': 'استشارة مجانية',
    'services.ctaAr': 'احجز استشارة مجانية',
    'service1.title': 'كتب وملفات PDF',
    'service1.titleAr': 'كتب وملفات PDF',
    'service1.desc': 'تصميم كامل، تنسيق، كتب طبية ومنشورات رقمية — جاهزة للطباعة.',
    'service2.title': 'عروض تقديمية',
    'service2.titleAr': 'عروض تقديمية',
    'service2.desc': 'محاضرات طبية، مؤتمرات وشرائح مؤسسية تتواصل بسلطة.',
    'service3.title': 'خرائط ذهنية',
    'service3.titleAr': 'خرائط ذهنية',
    'service3.desc': 'مسارات بصرية ومخططات سريرية تجعل التعقيد واضحًا فورًا.',
    'service4.title': 'ملخصات وبنوك أسئلة',
    'service4.titleAr': 'ملخصات وبنوك أسئلة',
    'service4.desc': 'بنوك أسئلة MCQ، بطاقات دراسية ومقتطفات بصرية تضغط التعقيد إلى وضوح.',
    'about.title': 'نبذة عني',
    'about.heading': 'حيث يلتقي التصميم مع',
    'about.headingHighlight': 'الطب.',
    'about.bio1': 'أنا د. عبدالرحمن م. حافظ، مصمم محتوى طبي ومحرر متخصص مقره القاهرة، مع تركيز عميق على المجالات الطبية والأكاديمية.',
    'about.bio2': 'المحتوى الطبي المصمم جيدًا لا يبدو جيدًا فقط — يساعد الطلاب على التعلم بشكل أسرع، والأطباء على الاستذكال بشكل أفضل، والمؤسسات على التواصل بسلطة.',
    'about.tools': 'الأدوات والبرامج',
    'about.experience': 'الخبرة',
    'contact.title': 'ابدأ محادثة',
    'contact.heading': 'لنصنع شيئًا',
    'contact.headingHighlight': 'يستحق القراءة.',
    'contact.tagline': 'لنصنع شيئاً يستحق القراءة.',
    'contact.waLabel': 'أسرع رد',
    'contact.waTitle': 'تواصل عبر واتساب',
    'contact.waHint': 'أرد في دقائق.',
    'contact.emailLabel': 'البريد',
    'contact.emailTitle': 'hello@hafez.design',
    'contact.locationLabel': 'الموقع',
    'contact.locationTitle': 'القاهرة، مصر · عن بُعد عالميًا',
    'contact.locationAr': 'القاهرة، مصر · متاح للعمل عن بُعد',
    'contact.formTitle': 'أرسل رسالة',
    'contact.formHint': 'أو راسلني مباشرة على واتساب لرد أسرع.',
    'contact.nameLabel': 'الاسم *',
    'contact.namePlaceholder': 'اسمك',
    'contact.nameError': 'الرجاء إدخال الاسم.',
    'contact.emailLabel2': 'البريد *',
    'contact.emailPlaceholder': 'you@example.com',
    'contact.emailError': 'الرجاء إدخال بريد إلكتروني صحيح.',
    'contact.serviceLabel': 'الخدمة *',
    'contact.servicePlaceholder': 'اختر خدمة…',
    'contact.serviceError': 'الرجاء اختيار خدمة.',
    'contact.messageLabel': 'الرسالة *',
    'contact.messagePlaceholder': 'أخبرني عن مشروعك…',
    'contact.messageError': 'الرجاء إدخال رسالة.',
    'contact.submitBtn': 'إرسال الرسالة',
    'contact.waBtn': 'راسلني على واتساب',
    'contact.directEmail': 'أو أرسل بريدًا مباشرًا: hello@hafez.design',
    'footer.name': 'د. عبدالرحمن م.',
    'footer.backToTop': 'العودة للأعلى',
    'footer.copyright': '2026',
    'toast.message': 'تم إرسال الرسالة — سأرد خلال 24 ساعة.',
  }
};

export function useLanguage() {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    return (localStorage.getItem('portfolio-language') as Language) || 'en';
  });

  useEffect(() => {
    const html = document.documentElement;
    html.lang = lang;
    html.dir = lang === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('portfolio-language', lang);
  }, [lang]);

  const setLang = useCallback((l: Language) => setLangState(l), []);
  const toggle = useCallback(() => setLangState(prev => prev === 'en' ? 'ar' : 'en'), []);

  const t = useCallback((key: string) => {
    return translations[lang]?.[key as keyof typeof translations.en] || key;
  }, [lang]);

  return { lang, setLang, toggle, t, isAr: lang === 'ar' };
}
